### ISSUE TITLE
www.youtube.com not allowing connection

### ISSUE THREAD

**Issue by tasticad** [im-fahad/vue-player#3]
I'm setting the link source as `src="https://youtu.be/pnJAzq6ITMM"` and Youtube doesn't allow connection.

I don't have this problem with Vimeo.

**Comment by im-fahad** [comment]
I did not find any problem using your link source. Maybe it's your connection or regional issue. You can use the link like src = "https://www.youtube.com/watch?v=pnJAzq6ITMM"
